name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                
          - name: Find cross-compiler path
            run: |
              echo "=== Checking for package-managed aarch64 compiler ==="
              which aarch64-linux-gnu-gcc || true
              
              echo "=== Checking the exact location of any aarch64 compiler ==="
              find / -name "*aarch64*gcc*" 2>/dev/null || true
                  
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
              FORCE_UNSAFE_CONFIGURE: 1
              BR2_TOOLCHAIN_EXTERNAL_PATH: "/usr/local/arm-cross-compiler/install/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-linux-gnu"
            run: |
              ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
